version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.dockerfile
    image: frontend
    stdin_open: true  # Required for running the frontend server
    volumes:
      - "../:/app"
    networks:
      - router
  backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    image: backend
    env_file:
      - ../.flaskenv
    volumes:
      - "../:/app"
    networks:
      - router

networks:
  router:
    external:
      name: router_router
