version: '3'

services:
  frontend:
    build:
      context: ..
      dockerfile: docker/frontend.dockerfile
    image: frontend
    stdin_open: true
    volumes:
      - "../:/app"
  backend:
    build:
      context: ..
      dockerfile: docker/backend.dockerfile
    image: backend
    env_file:
      - ../.flaskenv
    volumes:
      - "../:/app"
  router:
    build:
      context: ..
      dockerfile: docker/nginx.dockerfile
    image: router
    ports:
      - "80:80"
